export const CLOCKPOINT_LIST_REQUEST = 'CLOCKPOINT_LIST_REQUEST';
export const CLOCKPOINT_LIST_SUCCESS = 'CLOCKPOINT_LIST_SUCCESS';
export const CLOCKPOINT_LIST_FAIL = 'CLOCKPOINT_LIST_FAIL';

export const CLOCKPOINT_SAVE_REQUEST = 'CLOCKPOINT_SAVE_REQUEST';
export const CLOCKPOINT_SAVE_SUCCESS = 'CLOCKPOINT_SAVE_SUCCESS';
export const CLOCKPOINT_SAVE_FAIL = 'CLOCKPOINT_SAVE_FAIL';

export const CLOCKPOINT_DELETE_REQUEST = 'CLOCKPOINT_DELETE_REQUEST';
export const CLOCKPOINT_DELETE_SUCCESS = 'CLOCKPOINT_DELETE_SUCCESS';
export const CLOCKPOINT_DELETE_FAIL = 'CLOCKPOINT_DELETE_FAIL';

export const CLOCKPOINT_UPDATE_REQUEST = 'CLOCKPOINT_UPDATE_REQUEST';
export const CLOCKPOINT_UPDATE_SUCCESS = 'CLOCKPOINT_UPDATE_SUCCESS';
export const CLOCKPOINT_UPDATE_FAIL = 'CLOCKPOINT_UPDATE_FAIL';